language: objective-c
matrix:
  include:
    - os: osx
      osx_image: xcode9.1
    - os: osx
      osx_image: xcode8.3
cache:
  bundler: true
  cocoapods: true
  directories: []
branches:
  only:
    - travis
    - dev
    - release
    - master
before_install:
  - rvm get stable --auto-dotfiles
  - rvm use 2.3 --install --binary --fuzzy
  - (ruby --version)
  - sudo motion update
script:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake clean
  - bundle exec rake spec
after_success:
  - bash <(curl -s https://codecov.io/bash)
